### ISSUE TITLE
Range 12 RW AR scenario needs briefing entry

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-vWing/ATRM_Brief#34]
https://github.com/132nd-vWing/ATRM/issues/109

@132nd-Inigo

**Comment by 132nd-Inigo** [comment]
**Scenario**

Intelligence reports presence of a new SA-6 SAM installation in a valley at GRID DP17. RED FORCE are expected to be aware of BLUE FORCE Air Assets and are likely start their preparations for an offensive against BLUE FORCE under the cover of said SAM site. It is likely that the SAM site is protected by a mechanized platoon protected SHORAD or IR-SAM.
Due to air cover presented by the SA-6 SAM site, RED FORCE most likely course of action is to dispatch a scout platoon to scout possible attack routes into Ras Al Khaiman Airport. In addition, a transport vehicle has been reported at GRID DP06 carrying multiple infantry units, which are likely to be equipped with a 9K38 Igla MANPAD launcher.

**Threats**

SA-6 SAM site protected by mechanized platoon at GRID DP17.
Possible 9K38 Igla MANPAD equipped infantry platoon at GRID DP06.

**DEAD Mission**

Your mission is to conduct a DEAD mission at Killbox TIDE. Task 1: Confirm or deny RED FORCE movement SOUTH along the Killbox TIDE and destroy any RED FORCE scout platoons. Task 2: Locate and destroy SA-6 installation at GRID DP17

Target priority:
SAM radars and Launchers
Command and Control installations
Armored vehicles
Scout vehicles
Logistical units

**Admin**
Scenario needs to be activated via F10 menu before take-off.
Scenario is not compatible with Range 12 AR scenario. SA-6 site will engage flights operating at Killbox NEPTUNE
The killbox does not mean that flights need to be within the killbox at all times. The killbox indicates where the targets are expected, and when activating the killbox no one else will fly into the killbox without coordinating with the one tasked to use the killbox.
Civilian buildings within the killbox are part of the range complex, but are to be treated as civilian buildings.

**Comment by 132nd-Inigo** [comment]
Updated Combatflite and picture of Killbox.
Added a new layer Range 12 RW DEAD
![RW DEAD RANGE 12](https://user-images.githubusercontent.com/54333457/87227639-0c345d80-c3a5-11ea-8e9a-4663d6fa3d6e.PNG)

Link to .cf file: https://drive.google.com/file/d/17ZOhuiEchmb8S6GyImM1tg5XD7U1AKJN/view?usp=sharing
